version: "3"
services:


  #
  # 1. App stack.
  #

  # See https://github.com/wodby/node
  node:
    image: wodby/node:$NODE_TAG
    working_dir: /app
    command: $NODE_COMMAND
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"

  # See https://github.com/wodby/nginx
  nginx:
    image: wodby/nginx:$NGINX_TAG
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_VHOST_PRESET: php
      NGINX_SERVER_ROOT: /var/www/html/public
    volumes:
      - ./app:/var/www/html
    ports:
      - "80:80"

  # See https://github.com/wodby/php
  php:
    image: wodby/php:$PHP_TAG
    depends_on:
      - "postgres"
    environment:
      DB_HOST: $DB_HOST
      DB_DRIVER: $DB_DRIVER
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      PHP_FPM_USER: app
      PHP_FPM_GROUP: app
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
    volumes:
      - ./app:/var/www/html

  # See https://github.com/wodby/postgres
  postgres:
    image: wodby/postgres:$POSTGRES_TAG
    stop_grace_period: 30s
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - ./data/db/default:/var/lib/postgresql/data

  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.2
    depends_on:
      - "postgres"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://$DB_USER:$DB_PASSWORD@$DB_HOST:5432/$DB_NAME
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    ports:
      - "8080:8080"


  #
  # 2. Dev tools.
  #

  adminer:
    image: wodby/adminer:$ADMINER_TAG
    environment:
      ADMINER_DEFAULT_DB_DRIVER: $DB_DRIVER
      ADMINER_DEFAULT_DB_HOST: $DB_HOST
      ADMINER_DEFAULT_DB_NAME: $DB_NAME
    ports:
      - "9000:9000"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025" # HTTP (UI)
      # - "1025:1025" # SMTP (no exposition needed)
